### 201
POST http://localhost:5000/api/phones
Content-Type: application/json

{
    "number":"+38233333333",
    "type":"mobile",
    "owner":"69e1125096cc4bce87a2c2e7"
}

### 200
GET http://localhost:5000/api/phones
