### 201
POST http://localhost:5000/api/phones
Content-Type: application/json

{
    "number":"+38233333333",
    "type":"mobile",
    "owner":"69e1125096cc4bce87a2c2e7"
}

### 200
GET http://localhost:5000/api/phones


### 200
GET http://localhost:5000/api/phones/69e665021d55a925ba1c5408

### 200 {}
PATCH http://localhost:5000/api/phones/69e6795c142b2cffac666e02
Content-Type: application/json

{
    "number":"+38244433333",
    "type":"work"
}

###
DELETE http://localhost:5000/api/phones/69e665021d55a925ba1c5408